functionsDirectory = "/mnt/c/Users/jacob/projects/home-kitchen-uk/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/mnt/c/Users/jacob/projects/home-kitchen-uk/src"
publishOrigin = "config"
functions = "/mnt/c/Users/jacob/projects/home-kitchen-uk/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]